<?php
/** @var \ConferenceTools\Speakers\Domain\Dashboard\Entity\Speaker $speaker */
$speaker = $this->speaker
?>
<div class="row">
    <div class="col-md-6">
        <div class="card spur-card">
            <div class="card-header">
                <div class="spur-card-icon">
                    <i class="fas fa-table"></i>
                </div>
                <div class="spur-card-title">Speaker Profile</div>
            </div>
            <div class="card-body ">
                <dl>
                    <dt>Name</dt><dd><?=$speaker->getName()?></dd>
                    <dt>Email</dt><dd><?=$speaker->getEmail()?></dd>
                    <dt>Twitter</dt><dd><?=$speaker->getTwitter()?></dd>
                    <dt>Company</dt><dd><?=$speaker->getCompany()?></dd>
                    <dt>Bio</dt><dd><?=$speaker->getAboutMe()?></dd>
                    <dt>Dietary Preference</dt><dd><?=ucfirst($speaker->getPreference())?></dd>
                    <dt>Allergies</dt><dd><?=$speaker->getAllergies()?></dd>
                    <dt>Accessibility requirements</dt><dd><?=$speaker->getSpecialRequirements()?></dd>
                </dl>
                <a class="btn btn-primary" href="<?=$this->url('speakers/speaker/edit', ['speakerId' => $speaker->getIdentity()])?>">Edit</a>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="card spur-card">
            <div class="card-header">
                <div class="spur-card-icon">
                    <i class="fas fa-table"></i>
                </div>
                <div class="spur-card-title">Talks</div>
            </div>
            <div class="card-body ">
                <table class="table table-in-card">
                    <thead>
                    <tr><th>Title</th><th>Abstract</th><th></th></tr>
                    </thead>
                    <tbody>
                    <?php foreach ($speaker->getTalks() as $talk): ?>
                        <tr>
                            <td><?=$talk->getTitle()?></td>
                            <td><?=$talk->getAbstract()?></td>
                            <td>
                                <a class="btn btn-primary" href="<?=$this->url('speakers/talk/edit', ['talkId' => $talk->getIndex(), 'speakerId' => $speaker->getIdentity()])?>">Edit</a>
                                <a class="btn btn-danger" href="<?=$this->url('speakers/talk/cancel', ['talkId' => $talk->getIndex(), 'speakerId' => $speaker->getIdentity()])?>">Cancel</a>
                            </td>
                        </tr>
                    <?php endforeach;?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <div class="card spur-card">
            <div class="card-header">
                <div class="spur-card-icon">
                    <i class="fas fa-table"></i>
                </div>
                <div class="spur-card-title">Travel Reimbursement</div>
            </div>
            <div class="card-body ">
                <p>Display info on reimbursments</p>
                <a>Request travel reimbursement</a>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="card spur-card">
            <div class="card-header">
                <div class="spur-card-icon">
                    <i class="fas fa-table"></i>
                </div>
                <div class="spur-card-title">Station pickups</div>
            </div>
            <div class="card-body ">
                <p>Display info on station/airport pickups</p>
                <a>Request station/airport pickup</a>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <div class="card spur-card">
            <div class="card-header">
                <div class="spur-card-icon">
                    <i class="fas fa-table"></i>
                </div>
                <div class="spur-card-title">Accommodation details</div>
            </div>
            <div class="card-body ">
                <p>information on hotel rooms requested</p>

            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="card spur-card">
            <div class="card-header">
                <div class="spur-card-icon">
                    <i class="fas fa-table"></i>
                </div>
                <div class="spur-card-title">Speaker dinner/activities</div>
            </div>
            <div class="card-body ">
                <p>Details about said activities</p>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="card spur-card">
            <div class="card-header">
                <div class="spur-card-icon">
                    <i class="fas fa-table"></i>
                </div>
                <div class="spur-card-title">Travel Details</div>
            </div>
            <div class="card-body ">
                <table class="table table-in-card">
                    <thead>
                    <tr><th>Depart From</th><th>Departure Time</th><th>Arrive At</th><th>Arrival Time</th><th>Notes</th></tr>
                    </thead>
                    <tbody>
                    <?php foreach ($speaker->getJourneys() as $journey): ?>
                        <tr>
                            <td><?=$journey->getDepartFrom()?></td>
                            <td><?=$journey->getDepartureTime()->format('Y-m-d h:i')?></td>
                            <td><?=$journey->getArriveAt()?></td>
                            <td><?=$journey->getArrivalTime()->format('Y-m-d h:i')?></td>
                            <td><?=$journey->getNotes()?></td>
                        </tr>
                    <?php endforeach;?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>