<?php
/** @var \ConferenceTools\Speakers\Domain\Dashboard\Entity\Speaker $speaker */
$speaker = $this->speaker
?>
<div class="row">
    <div class="col-md-6">
        <div class="card spur-card">
            <div class="card-header">
                <div class="spur-card-icon">
                    <i class="fas fa-table"></i>
                </div>
                <div class="spur-card-title">Speaker Profile</div>
            </div>
            <div class="card-body ">
                <dl>
                    <dt>Name</dt><dd><?=$this->escapeHtml($speaker->getName())?></dd>
                    <dt>Email</dt><dd><?=$this->escapeHtml($speaker->getEmail())?></dd>
                    <dt>Twitter</dt><dd><?=$this->escapeHtml($speaker->getTwitter())?></dd>
                    <dt>Company</dt><dd><?=$this->escapeHtml($speaker->getCompany())?></dd>
                    <dt>Bio</dt><dd><?=$this->escapeHtml($speaker->getAboutMe())?></dd>
                    <dt>Dietary Preference</dt><dd><?=ucfirst($speaker->getPreference())?></dd>
                    <dt>Allergies</dt><dd><?=$this->escapeHtml($speaker->getAllergies())?></dd>
                    <dt>Accessibility requirements</dt><dd><?=$this->escapeHtml($speaker->getSpecialRequirements())?></dd>
                </dl>
                <a class="btn btn-primary" href="<?=$this->url('speakers/speaker/edit', ['speakerId' => $speaker->getIdentity()])?>">Edit</a>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="card spur-card">
            <div class="card-header">
                <div class="spur-card-icon">
                    <i class="fas fa-table"></i>
                </div>
                <div class="spur-card-title">Talks</div>
            </div>
            <div class="card-body ">
                <table class="table table-in-card">
                    <thead>
                    <tr><th>Title</th><th>Abstract</th><th></th></tr>
                    </thead>
                    <tbody>
                    <?php foreach ($speaker->getTalks() as $talk): ?>
                        <tr>
                            <td><?=$this->escapeHtml($talk->getTitle())?></td>
                            <td><?=$this->escapeHtml($talk->getAbstract())?></td>
                            <td>
                                <a class="btn btn-primary" href="<?=$this->url('speakers/speaker/talk/edit', ['talkId' => $talk->getIndex(), 'speakerId' => $speaker->getIdentity()])?>">Edit</a>
                                <a class="btn btn-danger" href="<?=$this->url('speakers/speaker/talk/cancel', ['talkId' => $talk->getIndex(), 'speakerId' => $speaker->getIdentity()])?>">Cancel</a>
                            </td>
                        </tr>
                    <?php endforeach;?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <div class="card spur-card">
            <div class="card-header">
                <div class="spur-card-icon">
                    <i class="fas fa-table"></i>
                </div>
                <div class="spur-card-title">Travel Reimbursement</div>
            </div>
            <div class="card-body ">
                <table class="table table-in-card">
                    <thead>
                    <tr><th>Amount</th><th>Status</th><th>Notes</th><th></th></tr>
                    </thead>
                    <tbody>
                    <?php foreach ($speaker->getTravelReimbursements() as $reimbursement): ?>
                        <tr>
                            <td>£<?=$reimbursement->getAmount() / 100?></td>
                            <td><?=$reimbursement->getStatus()?></td>
                            <td>
                                <?php if ($reimbursement->getRequestNotes() !== ''): ?>
                                    <p><?=$this->escapeHtml($reimbursement->getRequestNotes())?></p>
                                <?php endif?>
                                <?php if ($reimbursement->isRejected() && $reimbursement->getRejectReason() !== ''): ?>
                                    <p><?=$this->escapeHtml($reimbursement->getRejectReason())?></p>
                                <?php endif?>
                                <?php if ($reimbursement->isAccepted() && $reimbursement->getAcceptNotes() !== ''): ?>
                                    <p><?=$this->escapeHtml($reimbursement->getAcceptNotes())?></p>
                                <?php endif?>
                                <?php if ($reimbursement->isPaid() && $reimbursement->getPaymentNotes() !== ''): ?>
                                    <p><?=$this->escapeHtml($reimbursement->getPaymentNotes())?></p>
                                <?php endif?>
                            </td>
                            <td>
                                <?php if ($reimbursement->isRequested()):?>
                                <a class="btn btn-primary" href="<?=$this->url('speakers/speaker/travel-reimbursement/accept', ['reimbursementRequestId' => $reimbursement->getReimbursementRequestId(), 'speakerId' => $speaker->getIdentity()])?>">Accept</a>
                                <a class="btn btn-danger" href="<?=$this->url('speakers/speaker/travel-reimbursement/reject', ['reimbursementRequestId' => $reimbursement->getReimbursementRequestId(), 'speakerId' => $speaker->getIdentity()])?>">Reject</a>
                                <?php endif?>
                                <?php if ($reimbursement->isAccepted()):?>
                                <a class="btn btn-primary" href="<?=$this->url('speakers/speaker/travel-reimbursement/paid', ['reimbursementRequestId' => $reimbursement->getReimbursementRequestId(), 'speakerId' => $speaker->getIdentity()])?>">Paid</a>
                                <?php endif?>
                            </td>
                        </tr>
                    <?php endforeach;?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="card spur-card">
            <div class="card-header">
                <div class="spur-card-icon">
                    <i class="fas fa-table"></i>
                </div>
                <div class="spur-card-title">Station pickups</div>
            </div>
            <div class="card-body ">
                <table class="table table-in-card">
                    <thead>
                    <tr><th>Station</th><th>Pickup time</th><th>Status</th><th>Notes</th><th></th></tr>
                    </thead>
                    <tbody>
                    <?php foreach ($speaker->getPickupRequests() as $pickupRequest): ?>
                        <tr>
                            <td><?=$pickupRequest->getStation()?></td>
                            <td><?=$pickupRequest->getPickupTime()->format('Y/m/d H:i')?></td>
                            <td><?=$pickupRequest->getStatus()?></td>
                            <td>
                                <?php if ($pickupRequest->getRequestNotes() !== ''): ?>
                                    <p><?=$this->escapeHtml($pickupRequest->getRequestNotes())?></p>
                                <?php endif?>
                                <?php if ($pickupRequest->isRejected() && $pickupRequest->getRejectReason() !== ''): ?>
                                    <p><?=$this->escapeHtml($pickupRequest->getRejectReason())?></p>
                                <?php endif?>
                                <?php if ($pickupRequest->isAccepted() && $pickupRequest->getAcceptNotes() !== ''): ?>
                                    <p><?=$this->escapeHtml($pickupRequest->getAcceptNotes())?></p>
                                <?php endif?>
                            </td>
                            <td>
                                <?php if ($pickupRequest->isRequested()):?>
                                    <a class="btn btn-primary" href="<?=$this->url('speakers/speaker/station-pickup/accept', ['pickupRequestId' => $pickupRequest->getPickupRequestId(), 'speakerId' => $speaker->getIdentity()])?>">Accept</a>
                                    <a class="btn btn-danger" href="<?=$this->url('speakers/speaker/station-pickup/reject', ['pickupRequestId' => $pickupRequest->getPickupRequestId(), 'speakerId' => $speaker->getIdentity()])?>">Reject</a>
                                <?php endif?>
                            </td>
                        </tr>
                    <?php endforeach;?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <div class="card spur-card">
            <div class="card-header">
                <div class="spur-card-icon">
                    <i class="fas fa-table"></i>
                </div>
                <div class="spur-card-title">Accommodation requests</div>
            </div>
            <div class="card-body ">
                <?php if ($speaker->hasRequestedAccommodation()):?>
                    <?php $requestedDates = $speaker->getAccommodation();?>
                    <dl>
                        <?php foreach ($this->hotelDates as $date => $text):?>
                            <dt><?=$text?></dt><dd><?=(!isset($requestedDates[$date])?'Available':$requestedDates[$date])?></dd>
                        <?php endforeach; ?>
                    </dl>
                <?php else:?>
                    <p>No booking requested yet</p>
                <?php endif?>

            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="card spur-card">
            <div class="card-header">
                <div class="spur-card-icon">
                    <i class="fas fa-table"></i>
                </div>
                <div class="spur-card-title">Speaker dinner/activities</div>
            </div>
            <div class="card-body ">
                <p>Details about said activities</p>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="card spur-card">
            <div class="card-header">
                <div class="spur-card-icon">
                    <i class="fas fa-table"></i>
                </div>
                <div class="spur-card-title">Travel Details</div>
            </div>
            <div class="card-body ">
                <table class="table table-in-card">
                    <thead>
                    <tr><th>Depart From</th><th>Departure Time</th><th>Arrive At</th><th>Arrival Time</th><th>Notes</th></tr>
                    </thead>
                    <tbody>
                    <?php foreach ($speaker->getJourneys() as $journey): ?>
                        <tr>
                            <td><?=$this->escapeHtml($journey->getDepartFrom())?></td>
                            <td><?=$journey->getDepartureTime()->format('Y-m-d h:i')?></td>
                            <td><?=$this->escapeHtml($journey->getArriveAt())?></td>
                            <td><?=$journey->getArrivalTime()->format('Y-m-d h:i')?></td>
                            <td><?=$this->escapeHtml($journey->getNotes())?></td>
                        </tr>
                    <?php endforeach;?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>