<?php
/** @var \ConferenceTools\Speakers\Domain\Dashboard\Entity\Speaker $speaker */
$speaker = $this->speaker
?>
<div class="row">
    <div class="col-md-6">
        <div class="card spur-card">
            <div class="card-header">
                <div class="spur-card-icon">
                    <i class="fas fa-table"></i>
                </div>
                <div class="spur-card-title">Speaker Profile</div>
            </div>
            <div class="card-body ">
                <dl>
                    <dt>Name</dt><dd><?=$this->escapeHtml($speaker->getName())?></dd>
                    <dt>Email</dt><dd><?=$this->escapeHtml($speaker->getEmail())?></dd>
                    <dt>Twitter</dt><dd><?=$this->escapeHtml($speaker->getTwitter())?></dd>
                    <dt>Company</dt><dd><?=$this->escapeHtml($speaker->getCompany())?></dd>
                    <dt>Bio</dt><dd><?=$this->escapeHtml($speaker->getAboutMe())?></dd>
                    <dt>Dietary Preference</dt><dd><?=ucfirst($speaker->getPreference())?></dd>
                    <dt>Allergies</dt><dd><?=$this->escapeHtml($speaker->getAllergies())?></dd>
                    <dt>Accessibility requirements</dt><dd><?=$this->escapeHtml($speaker->getSpecialRequirements())?></dd>
                </dl>
                <a class="btn btn-primary" href="<?=$this->url('speakers/edit-profile')?>">Edit</a>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="card spur-card">
            <div class="card-header">
                <div class="spur-card-icon">
                    <i class="fas fa-table"></i>
                </div>
                <div class="spur-card-title">Talks</div>
            </div>
            <div class="card-body ">
                <table class="table table-in-card">
                    <thead>
                    <tr><th>Title</th><th>Abstract</th><th></th></tr>
                    </thead>
                    <tbody>
                    <?php foreach ($speaker->getTalks() as $talk): ?>
                        <tr>
                            <td><?=$this->escapeHtml($talk->getTitle())?></td>
                            <td><?=$this->escapeHtml($talk->getAbstract())?></td>
                            <td><a class="btn btn-primary" href="<?=$this->url('speakers/edit-talk', ['talkId' => $talk->getIndex()])?>">Edit</a></td>

                        </tr>
                    <?php endforeach;?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<div class="row">
<div class="col-md-12">
    <div class="card spur-card">
        <div class="card-header">
            <div class="spur-card-icon">
                <i class="fas fa-table"></i>
            </div>
            <div class="spur-card-title">Travel Details</div>
        </div>
        <div class="card-body ">
            <p>You can use this area to record your travel details to and from the event. Supply as much or as little detail as you wish.</p>
            <table class="table table-in-card">
                <thead>
                <tr><th>Depart From</th><th>Departure Time</th><th>Arrive At</th><th>Arrival Time</th><th>Notes</th></tr>
                </thead>
                <tbody>
                <?php foreach ($speaker->getJourneys() as $journey): ?>
                    <tr>
                        <td><?=$this->escapeHtml($journey->getDepartFrom())?></td>
                        <td><?=$journey->getDepartureTime()->format('Y-m-d h:i')?></td>
                        <td><?=$this->escapeHtml($journey->getArriveAt())?></td>
                        <td><?=$journey->getArrivalTime()->format('Y-m-d h:i')?></td>
                        <td><?=$this->escapeHtml($journey->getNotes())?></td>
                    </tr>
                <?php endforeach;?>
                </tbody>
            </table>
            <a class="btn btn-primary mt-4" href="<?=$this->url('speakers/travel/provide-details', ['speakerId' => $speaker->getIdentity()])?>">Provide travel details</a>
        </div>
    </div>
</div>
</div>

<div class="row">
    <div class="col-md-6">
        <div class="card spur-card">
            <div class="card-header">
                <div class="spur-card-icon">
                    <i class="fas fa-table"></i>
                </div>
                <div class="spur-card-title">Travel Reimbursement</div>
            </div>
            <div class="card-body ">
                <p>
                    PHP Yorkshire will reimburse all travel costs for speakers at this year's event. We have a soft limit of £200 per speaker to cover this, we aim to cover costs which
                    come in above this limit provided there is sufficient budget to do so.
                </p>
                <p>
                    We will aim to make all payments within 7 days of submission unless a) You are a workshop speaker or b) your request is for greater than the £200 limit. In both these
                    cases we will make payment after the conference, for workshop speakers this will be for your travel and any payment due under the profit share arrangement in a single
                    payment. For speakers over the limit we will pay out the £200 limit plus as much up to the full amount as possible.
                </p>
                <p>
                    If you would like us to pay out earlier or need the travel costs covering prior to purchase of tickets, please fill out the form and let us know in the notes that
                    you require this. We will then need you to submit a second request once the tickets are purchased containing the receipt for our records.
                </p>
                <table class="table table-in-card">
                    <thead>
                    <tr><th>Amount</th><th>Status</th><th>Notes</th></tr>
                    </thead>
                    <tbody>
                    <?php foreach ($speaker->getTravelReimbursements() as $reimbursement): ?>
                        <tr>
                            <td>£<?=$reimbursement->getAmount() / 100?></td>
                            <td><?=$reimbursement->getStatus()?></td>
                            <td>
                                <?php if ($reimbursement->getRequestNotes() !== ''): ?>
                                    <p><?=$this->escapeHtml($reimbursement->getRequestNotes())?></p>
                                <?php endif?>
                                <?php if ($reimbursement->isRejected() && $reimbursement->getRejectReason() !== ''): ?>
                                    <p><?=$this->escapeHtml($reimbursement->getRejectReason())?></p>
                                <?php endif?>
                                <?php if ($reimbursement->isAccepted() && $reimbursement->getAcceptNotes() !== ''): ?>
                                    <p><?=$this->escapeHtml($reimbursement->getAcceptNotes())?></p>
                                <?php endif?>
                                <?php if ($reimbursement->isPaid() && $reimbursement->getPaymentNotes() !== ''): ?>
                                    <p><?=$this->escapeHtml($reimbursement->getPaymentNotes())?></p>
                                <?php endif?>
                            </td>
                        </tr>
                    <?php endforeach;?>
                    </tbody>
                </table>
                <a class="btn btn-primary mt-4" href="<?=$this->url('speakers/travel/request-reimbursement', ['speakerId' => $speaker->getIdentity()])?>">Request travel reimbursement</a>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="card spur-card">
            <div class="card-header">
                <div class="spur-card-icon">
                    <i class="fas fa-table"></i>
                </div>
                <div class="spur-card-title">Station pickups</div>
            </div>
            <div class="card-body ">
                <p>
                    If you are arriving at either Leeds Bradford airport or York train station, we can organise a pickup for you. Where possible this will be a member
                    of the PHP Yorkshire team, however as this is a small group of people, this is not always possible.
                </p>
                <p>
                    If we are unable to make it to a pickup ourselves, we will reject the request. You then have two options, either submit a
                    second request and we'll arrange for a taxi to pick you up or you can arrange your own taxi upon arrival.
                    If you book your own taxi please keep the reciept so that we can refund the cost.
                </p>

                <table class="table table-in-card">
                    <thead>
                    <tr><th>Station</th><th>Pickup time</th><th>Status</th><th>Notes</th></tr>
                    </thead>
                    <tbody>
                    <?php foreach ($speaker->getPickupRequests() as $pickupRequest): ?>
                        <tr>
                            <td><?=$pickupRequest->getStation()?></td>
                            <td><?=$pickupRequest->getPickupTime()->format('Y/m/d H:i')?></td>
                            <td><?=$pickupRequest->getStatus()?></td>
                            <td>
                                <?php if ($pickupRequest->getRequestNotes() !== ''): ?>
                                    <p><?=$this->escapeHtml($pickupRequest->getRequestNotes())?></p>
                                <?php endif?>
                                <?php if ($pickupRequest->isRejected() && $pickupRequest->getRejectReason() !== ''): ?>
                                    <p><?=$this->escapeHtml($pickupRequest->getRejectReason())?></p>
                                <?php endif?>
                                <?php if ($pickupRequest->isAccepted() && $pickupRequest->getAcceptNotes() !== ''): ?>
                                    <p><?=$this->escapeHtml($pickupRequest->getAcceptNotes())?></p>
                                <?php endif?>
                            </td>
                        </tr>
                    <?php endforeach;?>
                    </tbody>
                </table>

                <a class="btn btn-primary mt-4" href="<?=$this->url('speakers/travel/request-pickup', ['speakerId' => $speaker->getIdentity()])?>">Request station/airport pickup</a>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <div class="card spur-card">
            <div class="card-header">
                <div class="spur-card-icon">
                    <i class="fas fa-table"></i>
                </div>
                <div class="spur-card-title">Accommodation details</div>
            </div>
            <div class="card-body ">
                <dl>
                    <dt>Accommodation name</dt><dd></dd>
                    <dt>Accommodation address</dt><dd></dd>
                    <dt>Accommodation phone number</dt><dd></dd>
                    <dt>Nights booked</dt><dd></dd>
                </dl>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="card spur-card">
            <div class="card-header">
                <div class="spur-card-icon">
                    <i class="fas fa-table"></i>
                </div>
                <div class="spur-card-title">Accommodation booking</div>
            </div>
            <div class="card-body ">
                <?php if ($speaker->hasRequestedAccommodation()):?>
                <?php $requestedDates = $speaker->getAccommodation();?>
                <dl>
                    <?php foreach ($this->hotelDates as $date => $text):?>
                        <dt><?=$text?></dt><dd><?=(!isset($requestedDates[$date])?'Available':$requestedDates[$date])?></dd>
                    <?php endforeach; ?>
                </dl>
                <?php else:?>
                <p>No booking requested yet</p>
                <?php endif?>

                <a class="btn btn-primary mt-4" href="<?=$this->url('speakers/hotel')?>">Book nights</a>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <div class="card spur-card">
            <div class="card-header">
                <div class="spur-card-icon">
                    <i class="fas fa-table"></i>
                </div>
                <div class="spur-card-title">Venue information</div>
            </div>
            <div class="card-body ">
                <dl>
                    <dt>Name</dt><dd></dd>
                    <dt>Address</dt><dd></dd>
                    <dt>Dates</dt><dd></dd>
                </dl>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="card spur-card">
            <div class="card-header">
                <div class="spur-card-icon">
                    <i class="fas fa-table"></i>
                </div>
                <div class="spur-card-title">Av information</div>
            </div>
            <div class="card-body ">
                <p>Add information here about AV details</p>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <div class="card spur-card">
            <div class="card-header">
                <div class="spur-card-icon">
                    <i class="fas fa-table"></i>
                </div>
                <div class="spur-card-title">Speaker dinner/activities</div>
            </div>
            <div class="card-body ">
                <p>Details about said activities</p>
                <a>RSVP</a>
            </div>
        </div>
    </div>
</div>