<div class="row">
    <div class="col-md-12">
        <div class="card spur-card">
            <div class="card-header">
                <div class="spur-card-icon">
                    <i class="fas fa-table"></i>
                </div>
                <div class="spur-card-title">Travel Reimbursement Requests</div>
            </div>
            <div class="card-body ">
                <table class="table table-in-card">
                    <thead>
                    <tr><th>Speaker</th><th>Amount</th><th>Status</th><th></th></tr>
                    </thead>
                    <tbody>
                    <?php foreach ($this->travelReimbursements as $travelReimbursement): ?>
                        <?php
                        /** @var \ConferenceTools\Speakers\Domain\Dashboard\Entity\TravelReimbursement $travelReimbursement */
                        $speaker = $travelReimbursement->getSpeaker();?>
                        <tr>
                            <td><a href="<?=$this->url('speakers/speaker', ['speakerId' => $speaker->getIdentity()])?>"><?=$this->escapeHtml($speaker->getName())?></a></td>
                            <td>£<?=$travelReimbursement->getAmount() / 100?></td>
                            <td><?=$travelReimbursement->getStatus()?></td>
                            <td>
                                <?php if ($travelReimbursement->isRequested()):?>
                                    <a class="btn btn-primary" href="<?=$this->url('speakers/speaker/travel-reimbursement/accept', ['reimbursementRequestId' => $travelReimbursement->getReimbursementRequestId(), 'speakerId' => $speaker->getIdentity()])?>">Accept</a>
                                    <a class="btn btn-danger" href="<?=$this->url('speakers/speaker/travel-reimbursement/reject', ['reimbursementRequestId' => $travelReimbursement->getReimbursementRequestId(), 'speakerId' => $speaker->getIdentity()])?>">Reject</a>
                                <?php endif?>
                                <?php if ($travelReimbursement->isAccepted()):?>
                                    <a class="btn btn-primary" href="<?=$this->url('speakers/speaker/travel-reimbursement/paid', ['reimbursementRequestId' => $travelReimbursement->getReimbursementRequestId(), 'speakerId' => $speaker->getIdentity()])?>">Paid</a>
                                <?php endif?>
                            </td>
                        </tr>
                    <?php endforeach;?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>